---
# roles/nessus_agent/tasks/main.yml
- name: Download Nessus agent
  get_url:
    url: "{{ nessus_agent_url }}"
    dest: /tmp/NessusAgent.rpm

- name: Install Nessus agent
  dnf:
    name: /tmp/NessusAgent.rpm
    state: present

- name: Enable Nessus agent
  systemd:
    name: nessus-agent
    enabled: true
    state: started
